const english: Record<string, string> = {
  'Créez votre premier raccourci.': 'Create your first shortcut.',
  'Ajoutez et configurez vos boutons dans la sidebar MyWallpaper.': 'Add and configure your buttons in the MyWallpaper sidebar.',
  'Impossible de charger la configuration.': 'Could not load configuration.',
  'Choisissez d’abord une cible.': 'Choose a target first.',
  'Lancer ce bouton': 'Launch this button',
  'Boutons': 'Buttons', 'Ajouter un bouton': 'Add a button', 'Importer du bureau': 'Import desktop shortcuts',
  'Configuration': 'Configuration', 'Importer un fichier': 'Import a file', 'Exporter': 'Export',
  'Les chemins locaux restent sur cet appareil. Une sauvegarde JSON inclut ces chemins, sans les fichiers médias.': 'Local paths stay on this device. A JSON backup includes these paths, without the media files.',
  'Surface': 'Surface', 'Opacité': 'Opacity', 'Langue': 'Language', 'Automatique': 'Automatic',
  'Nom': 'Name', 'Afficher le nom': 'Show label', 'Action': 'Action',
  'Chemin ou lien': 'Path or link',
  'Les chemins Windows restent locaux ; les liens HTTP(S) et mailto suivent la disposition.': 'Windows paths stay local; HTTP(S) and mailto links follow the layout.',
  'Arguments': 'Arguments', 'Choisir un fichier ou une application': 'Choose a file or application', 'Choisir un dossier': 'Choose a folder',
  'Apparence': 'Appearance', 'Forme': 'Shape', 'Rectangle': 'Rectangle', 'Ellipse': 'Ellipse', 'Triangle': 'Triangle', 'Hexagone': 'Hexagon',
  'Arrondi': 'Corner radius', 'Couleur': 'Color', 'Icône': 'Icon',
  'Application': 'Application', 'Dossier': 'Folder', 'Fichier': 'File', 'Lien': 'Link', 'Musique': 'Music', 'Image': 'Image',
  'Média': 'Media', 'Type': 'Type', 'Aucun': 'None', 'Vidéo': 'Video',
  'Chemin ou lien HTTPS': 'Path or HTTPS link', 'Choisir un média': 'Choose media',
  'Vidéo au survol uniquement': 'Play video only on hover',
  'Dimensions et position': 'Size and position', 'Position': 'Position', 'Dimensions': 'Size', 'Largeur': 'Width', 'Hauteur': 'Height',
  'Dupliquer': 'Duplicate', 'Supprimer': 'Delete', 'Tester le raccourci': 'Test shortcut',
  'Choisir les raccourcis': 'Choose shortcuts', 'Tout sélectionner': 'Select all',
  'Les fichiers d’origine restent intacts.': 'Original files remain unchanged.',
  'Importer la sélection': 'Import selection', 'Annuler l’import': 'Cancel import',
  'Confirmer le remplacement': 'Confirm replacement',
  'La disposition actuelle sera remplacée. Les chemins locaux du fichier restent sur cet appareil.': 'The current layout will be replaced. Local paths in the file stay on this device.',
  'Aucun raccourci trouvé sur le bureau.': 'No desktop shortcuts found.',
  'La configuration est trop volumineuse.': 'The configuration is too large.',
  'La limite de 1024 boutons est atteinte.': 'The limit of 1024 buttons has been reached.',
}
export const translate = (text: string, french: boolean): string => french ? text : (english[text] ?? text)
